DROP DATABASE IF EXISTS familydcotor;

CREATE DATABASE familydoctor;

USE familydoctor;

CREATE TABLE Address(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STREET VARCHAR(10) NOT NULL,
    CITY VARCHAR(10) NOT NULL,
    STATE VARCHAR(2),
    ZIP VARCHAR(5)
) AUTO_INCREMENT = 100;

CREATE TABLE PatientAccount(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(10) NOT NULL,
    LAST_NAME VARCHAR(10) NOT NULL,
	PHONE NUMERIC(10,0) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	SSN VARCHAR(30) NOT NULL,
    ADDRESS_ID INTEGER NOT NULL,
    FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID)
) AUTO_INCREMENT = 100;

CREATE TABLE DoctorAccount(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(10) NOT NULL,
    LAST_NAME VARCHAR(10) NOT NULL,
	PHONE NUMERIC(10,0) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	SPECIALIZATION VARCHAR(10) NOT NULL,
	LISENCE_NUM VARCHAR(10) NOT NULL,
    ADDRESS_ID INTEGER NOT NULL,
    FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID)
) AUTO_INCREMENT = 100;


CREATE TABLE AdminAccount(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	STAFF_NUM INTEGER NOT NULL,
    FIRST_NAME VARCHAR(10) NOT NULL,
    LAST_NAME VARCHAR(10) NOT NULL,
	PHONE NUMERIC(10,0) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
    ADDRESS_ID INTEGER NOT NULL,
	FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID)
) AUTO_INCREMENT = 100;


CREATE TABLE Appointment(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STATUS BOOLEAN NOT NULL,
    ROOM INTEGER NOT NULL,
	DATE DATE NOT NULL,
	INVOICE_ID INTEGER NOT NULL,
    PATIENT_ID INTEGER NOT NULL,	
    DOCTOR_ID INTEGER NOT NULL,
    FOREIGN KEY (INVOICE_ID) REFERENCES Invoice(ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PatientAccount(ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DoctorAccount(ID)
) AUTO_INCREMENT = 100;


CREATE TABLE Invoice(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	AMOUNT DOUBLE NOT NULL,
    STATUS BOOLEAN NOT NULL,
    CCARD_4D NUMERIC(4,0),
	DATE_CREATED DATE NOT NULL,
	DATE_PAID DATE NOT NULL,
    APPOINTMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (APPOINTMENT_ID) REFERENCES Appointment(ID)
) AUTO_INCREMENT = 100;
